### ISSUE TITLE
libtest-mimic v 0.6 docs are broken on docs.rs

### ISSUE THREAD

**Issue by DanielJoyce** [LukasKalbertodt/libtest-mimic#22] opened 2023-01-12 20:29 UTC
https://docs.rs/libtest-mimic/0.5.2/libtest_mimic/index.html  << Renders fine

https://docs.rs/libtest-mimic/0.6.0/libtest_mimic/index.html << Broken

Confirmed its not my local browser caching a docs.rs hiccup

**Comment by LukasKalbertodt** [comment] 2023-01-13 09:04
Can you describe how they are broken for you? Looks fine to me:

![image](https://user-images.githubusercontent.com/7419664/212280841-8989095e-3fad-4d13-8eaf-c9e921dcac56.png)

**Comment by DanielJoyce** [comment] 2023-01-13 19:40
This is how it renders:

![image](https://user-images.githubusercontent.com/947350/212404824-dafd72ab-693c-4929-acfb-179d1f4b2382.png)

Errors in the console

![image](https://user-images.githubusercontent.com/947350/212405019-7f6d6dc4-f377-4f0b-a30c-aeac9c71c632.png)

**Comment by DanielJoyce** [comment] 2023-01-13 19:42
Are you using a custom theme? Because all the links are broken when I visit.

**Comment by DanielJoyce** [comment] 2023-01-13 19:43
One of the urls that gets a 404 for me

`https://docs.rs/-/rustdoc.static/normalize-20221104-1.67.0-nightly-09508489e.css`

**Comment by DanielJoyce** [comment] 2023-01-13 19:45
![image](https://user-images.githubusercontent.com/947350/212405657-3b93b9d9-2875-4c55-a077-d8d71861c012.png)

**Comment by DanielJoyce** [comment] 2023-01-13 19:57
I've turned caching, flushed cache, and used a incognito window. All are still broke

I'm worried by the broken URLS all seem to mention 1.67-nightly somehow?

**Comment by DanielJoyce** [comment] 2023-01-13 20:55
The broken urls in 0.6.0 show https://docs.rs/-/

The working ones in 0.5.2 don't have the /-/ path component?

**Comment by DanielJoyce** [comment] 2023-01-13 20:59
Just tried firefox, broken there as well

**Comment by LukasKalbertodt** [comment] 2023-01-15 11:49
> Are you using a custom theme? 

Nope.



> One of the urls that gets a 404 for me
> 
> `https://docs.rs/-/rustdoc.static/normalize-20221104-1.67.0-nightly-09508489e.css`

Nope, works for me: returns a CSS file.

> I'm worried by the broken URLS all seem to mention 1.67-nightly somehow?

That's for me as well, so that seems normal.

---

But wow, that seems weird, especially given that you also tried a different browser. My best guesses are: you are behind some firewall, or are using some kind of VPN or proxy, or something like that. Or maybe a browser extension that you have installed in both browsers?

But as I cannot reproduce this (I tried on multiple devices), I will close this issue. This is not something I can fix.

**Closed as completed by LukasKalbertodt** 2023-01-15 11:49 UTC

**Comment by DanielJoyce** [comment] 2023-01-19 02:49
So all of those URLS work for you and you see nothing broken in your browser?

I just tried it on my phone, broken there as well.

**Comment by DanielJoyce** [comment] 2023-01-19 02:54
No proxy, vpn, or anything, i tried using wifi and 5g

**Comment by DanielJoyce** [comment] 2023-01-19 03:00
Filed a ticket in docs.rs in case they have a broken CDN or something. Thanks for your help.
